### ISSUE TITLE
[Bug] Evil pet tutorial may render text on the same line as PETC prompt 

### ISSUE THREAD

**Issue by Mighty-Moo** [skidoodl/My-First-Eldritch-Evil#20]
Occasionally during the text scroll in the evil pet tutorial, a line of text may occasionally appear on the same line as the previous "Press Enter to Continue" prompt, with no spacing. This likely occurs when the player provides input while the text is still rendering.

**Comment by Enilks** [comment]
Irrelevant due to v2.0
